[package]
name = "injector"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.155"
thiserror = "1.0.61"
procfs = "0.16.0"
scopeguard = "1.2.0"
nix = { version = "0.29.0", features = ["process"] }
